### ISSUE TITLE
Enhancement request: For Artifactory isar should get the checksum via API.

### ISSUE THREAD

**Issue by kumbasar** [ilbers/isar#40]
It would be great, if isar (bitbake) is able to get the checksum for JForg Artifactory's using [1], automatically, not from "SRC_URI[sha256sum]" Or do we have a workaround to avoid hard coded checksum values in bb recipes. 

[1] http://forums.jfrog.org/How-to-verify-curl-wget-download-artifact-is-correct-td7580081.html

**Comment by alexbluesman** [comment]
Hello! Could you please describe your use-case? Am I right that you want to download binary files from recipe and do not want to manually hardcode checksums?

**Comment by Rondom** [comment]
Not specifying a checksum would make the build no longer reproducible, wouldn't it?

**Comment by alexbluesman** [comment]
On the one hand, yes, not specifying a checksum could mean non-reproducible build, but there are several other facts, like:
 - AUTOREV in bitbake which means to pull head commit
 - Upstream debian.org could be updated at any time
what can't gurantee reproducibility with fetching from the upstream.

Regarding specifying the checksum, I'd like to do this for binaries to handle broken downloads. For example:
 - Bitbake is trying to download 'abc.conf' from the upstream
 - File localtion in upstream had been changed, so 404 HTML page returned as payload for 'abc.conf'
 - Due to 'abc.conf' does not participate in build, the problem could be detected only during image running

**Comment by alexbluesman** [comment]
No feedback for 1 month.
