### ISSUE TITLE
Use master branch normally

### ISSUE THREAD

**Issue by jan-kiszka** [ilbers/isar#45]
We should start updating master like other projects do, ie. after qualifying next via reviews and CI to be probably stable. It's very misleading for observers that master is not normally maintained.

**Comment by ismagulb** [comment]
Yes, the intention has always been to sync with master about once a month.

We haven't always done that because the tree has become unstable. To address this, we've added more test cases to the CI and migrated it to a faster machine. Faster QEMU checking and more selective test infrastructure is under way.

We expect to release the next candidate shortly and release more often. If you have other ideas for detecting quality issues more quickly, please let us know.

Does this address your wish?

**Comment by jan-kiszka** [comment]
Just rename "<maintainer>-next" to "next" and current "next" to "master", and we have the desired effect: frequent updates without giving up on QA for master. It's pointless to delay master syncs longer than for a week or two if that phase already ensures CI completion and commit review.

**Comment by ismagulb** [comment]
My concern is:

1. People don't bother with tags and just clone master.

2. Detecting most issues takes at least 1-2 weeks.

Review and CI surely provide a base level of QA, but haven't detected important issues affecting many users. So, people would get a broken state, fixing which may take time. I don't see a point in apply-revert-apply, either, if one can just handle that carefully in a development branch.

OTOH, what is the problem with checking out next if one needs the latest development version? I think the confusion you refer to happens due to the infrequent syncs we have mostly had till now.

So, my suggestion is to start with monthly syncs and see how it works. In the future, we could consider moving to two-week cycles, but that would still require a way to detect important issues quickly (apart from higher release overhead and implications for patch handling during freezes).

WDYT?

**Comment by jan-kiszka** [comment]
Do not try to be smarter than other projects.

**Comment by ismagulb** [comment]
I wonder what is smart about Linux 2.6.8 with an ext3 corruption bug landing in Debian stable. The trend is there, but does it provide better user experience?

**Comment by jan-kiszka** [comment]
Release management is another thing. This is just about living some best-practice like https://github.com/siemens/jailhouse/blob/master/CONTRIBUTING.md#contribution-integration-process.

**Comment by ismagulb** [comment]
Thanks, this is more specific. The document defines syncing to master every three days. What should be done if an important problem is found in master?

**Comment by jan-kiszka** [comment]
Fix it or revert the bogus commit - master is not perfect.  It should just not be rebased (but that is already the case for your current next branch). And you won't find issues by waiting to merge. 3 days is just one definition for this project, but it was ok so far.

**Comment by ismagulb** [comment]
As discussed offline, we'd like to gradually change the process towards the following:
* Master is the main development branch and not a stable release. Next is a shorter-lived branch for CI, testing and early feedback.
* Sync with master once in about two weeks (or more often whenever appropriate).
* If a major problem exists in master, handle it with priority. If a major change has been recently merged into next, allow time to collect feedback and resolve issues. Plan merges to master so that both fit the two-week window; short extensions should be an exception.

Useful resource: https://trunkbaseddevelopment.com/

**Comment by myo73** [comment]
* Sent patch "isar: Update CONTRIBUTING" to the mailing list 
https://groups.google.com/d/msgid/isar-users/20190403100703.6990-1-mosipov%40ilbers.de.
describing procedure of syncing `master` with `next`.

* Performed sync of `master`  with the current `next` branch
